#aws_database_url: mysql-database-server.csyk75ifilol.us-east-1.rds.amazonaws.com:3306
local_database_url: localhost:3306

server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://${local_database_url}/cardanorecyclingdappdb
    username: root
    password: qawsedrf123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

